### ISSUE TITLE
Requst: Add a way to see the clipboard history without navigating through the subfolders.

### ISSUE THREAD

**Issue by amit-nayar** [Clipy/Clipy#373]
Would it be possible to have a setting that removes the "0-10", "11-20" folders and just displays a history list straight away?  This will save the extra arrow key presses to get into the subfolders, as usually I just want to look at the last 5 or 10 copies and don't care about anything older.

**Comment by mementorack** [comment]
Of course we can. Change the number and restart Clipy.

<img width="480" alt="Screenshot" src="https://user-images.githubusercontent.com/36942418/65043877-c67e5280-d996-11e9-8cb3-aa5234b37cb4.png">

**Comment by amit-nayar** [comment]
Thanks, I have that set to 0 but I still have to go through a menu to get to the clipboard history.  My suggestion is that when this is set to 0, you don't have to go through an extra menu to view the items. 
This is the menu I would like to get rid of:
<img width="278" alt="Screenshot 2019-09-18 at 10 13 00" src="https://user-images.githubusercontent.com/32914303/65134904-f8c29b00-d9fc-11e9-91ff-3a67e94a2ed9.png">

**Comment by mementorack** [comment]
I mean, you should set to another number rather than 0.
I think you want this menu:

<img width="169" alt="Screen Shot 2019-09-19 at 13 41 56" src="https://user-images.githubusercontent.com/36942418/65214160-e53e2f80-dae3-11e9-8ec0-5d1ff8e8452e.png">
<img width="480" alt="Screen Shot 2019-09-19 at 13 43 07" src="https://user-images.githubusercontent.com/36942418/65214161-e5d6c600-dae3-11e9-8f79-855e9aef9c19.png">

**Comment by amit-nayar** [comment]
Ooooh!  Yes, that's what I want!  I just didn't restart the app.  Thanks!  Sorry for taking your time :)
