### ISSUE TITLE
Feature Request: Provide way to delete individual entries from history

### ISSUE THREAD

**Issue by dannylevenson** [Clipy/Clipy#493]
Currently, if I want to remove a specific entry from the history, the only way I see to do that is to clear the entire history. Perhaps I'm missing something, but I would like to be able to activate Clipy, navigate to one of the items in the history and delete the selected item, perhaps by pressing the delete key.

**Comment by andrewkr** [comment]
I think that simply pressing the Delete key might lead to accidentally deleting items you didn't want to delete. But I also don't like the way that some applications try to guard against those accidents by asking for confirmation for every deletion! That gets tiring very quickly, in my opinion.

What I prefer is sliding/swiping the mouse or trackpad over the desired item gives it a more intentional feel. But I'm open to other suggestions.

All of that said, I'm not a programmer! I don't know how difficult it is to implement any of this.

**Comment by dannylevenson** [comment]
I don't really care what keyboard or mouse action is necessary to delete an item, but I really would like a way to remove one or more selected items. Even something as simple as right clicking on an item to get to a delete option.

**Comment by dannylevenson** [comment]
Barring the ability to remove an individual entry, is there a way to manually edit the history. Even if I have to quit Clipy, edit and restart Clipy, I would really like to be able to remove specific entries from Clipy history without clearing everything.

**Comment by dannylevenson** [comment]
For what it is worth, I have tried the beta feature "Delete history" where you assign a modifier to use with a mouse click to delete a specific entry from the history. This completely fills my needs. I suggest renaming it to "Delete item from history" so that it is clear that you are not deleting the whole history.

**Comment by amdp** [comment]
danny thank you!
