### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by 350050183** [Clipy/Clipy#89]
$ bundle exec pod install
Analyzing dependencies
Pre-downloading: `LoginServiceKit` from `https://github.com/Clipy/LoginServiceKit.git`, commit `ba5de4c850dba6dc597241913ca049a220a61316`
[!] Unable to find a specification for `RxOptional`

**Comment by Econa77** [comment]
@350050183 Please try `bundle exec pod repo update` and `bundle exec pod install` command.

**Comment by 350050183** [comment]
@Econa77 
$ bundle exec pod repo update
Updating spec repo `master`
Performing a deep fetch of the `master` specs repo to improve future performance


[!] /usr/bin/git fetch --unshallow

error: RPC failed; curl 56 SSLRead() return error -36
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by Econa77** [comment]
@350050183  This problem is `CocoaPods` or `git` issue.

Please try `sudo rm -rf ~/.cocoapods/repos/master` and `bundle exec pod setup` , `bundle exec pod repo update`
https://github.com/CocoaPods/CocoaPods/issues/5332

or 

Setting  global git config.
https://github.com/CocoaPods/CocoaPods/issues/5278
